#!/usr/bin/env bash
# Nightly SNAPSHOT copy of OpenELIS on this server (intended for the off-site server).
# A second, fully running OpenELIS ("oesnap") rebuilt every night from this
# server's standby database. Everything entered into it is DISCARDED at the
# next refresh and is NEVER sent back to the live system. Outbound
# integrations (analyzer bridge, FHIR push, remote source, Odoo, freezer
# polling) are switched off, and every page shows a red warning banner.
#
#   sudo ./scripts/ha/snapshot-refresh.sh          # rebuild now (~10 min)
#   sudo ./scripts/ha/snapshot-refresh.sh --stop   # stop and remove the snapshot
# Cron (02:00 every night):
#   0 2 * * * root /opt/openelis/scripts/ha/snapshot-refresh.sh >> /var/log/oesnap.log 2>&1
. "$(dirname "$0")/lib.sh"
SNAP=${HA_SNAPSHOT_DIR:-/srv/oe-snapshot}
PORT=${HA_SNAPSHOT_PORT:-9443}
SC() { docker compose -p oesnap --env-file "$HA_ROOT/.env" -f docker-compose.yml -f "$SNAP/compose.snapshot.yaml" "$@"; }

if [ "${1:-}" = --stop ]; then
  [ -f "$SNAP/compose.snapshot.yaml" ] && SC down --remove-orphans
  log "snapshot stopped"; exit 0
fi

db_running || die "the main database is not running on this server"
[ "$(in_recovery)" = t ] || log "NOTE: this server is the PRIMARY; the snapshot is taken from it"
mkdir -p "$SNAP"/{properties,logs/oeLogs,logs/tomcatLogs}

# --- configuration for the snapshot (regenerated each run) ----------------
cp -a configs/properties/. "$SNAP/properties/"
python3 - "$SNAP/properties/common.properties" <<'PY'
import re, sys
p = sys.argv[1]; s = open(p).read()
off = {  # outbound integrations OFF in the snapshot
  "org.openelisglobal.remote.source.uri": "", "org.openelisglobal.fhir.subscriber": "",
  "org.openelisglobal.crserver.uri": "", "org.openelisglobal.facilitylist.fhirstore": "",
  "org.openelisglobal.providerlist.fhirstore": "", "org.openelisglobal.odoo.enabled": "false",
  "org.openelisglobal.freezermonitoring.enabled": "false",
}
for k, v in off.items():
    s, n = re.subn(rf"^{re.escape(k)}\s*=.*$", f"{k}={v}", s, flags=re.M)
    if not n: s += f"\n{k}={v}\n"
open(p, "w").write(s)
PY
BANNER='<style>#oesnap-banner{position:fixed;top:0;left:0;right:0;height:32px;box-sizing:border-box;z-index:2147483647;background:#da1e28;color:#fff;font:600 13px/20px sans-serif;padding:6px 12px;text-align:center;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}body{padding-top:32px!important}.cds--header,.bx--header{top:32px!important}.cds--side-nav,.bx--side-nav{top:80px!important}</style><div id="oesnap-banner">SNAPSHOT COPY - NOT THE LIVE SYSTEM. Rebuilt every night. Anything entered here is DELETED at the next rebuild and NOT sent to the live system. Do not enter data.</div>'
python3 - configs/nginx/nginx.conf "$SNAP/nginx.conf" "$BANNER" <<'PY'
import sys
src, dst, banner = sys.argv[1:]
s = open(src).read()
inject = ('location / {\n            proxy_set_header Accept-Encoding "";\n'
          '            sub_filter_once on;\n'
          f"            sub_filter '<body>' '<body>{banner}';\n")
assert "location / {\n            proxy_pass http://frontend.openelis.org;" in s, "nginx.conf layout changed; update snapshot-refresh.sh"
s = s.replace("location / {\n            proxy_pass http://frontend.openelis.org;",
              inject + "            proxy_pass http://frontend.openelis.org;", 1)
open(dst, "w").write(s)
PY
cat > "$SNAP/compose.snapshot.yaml" <<YAML
# Generated by scripts/ha/snapshot-refresh.sh -- do not edit by hand.
services:
  certs:
    container_name: oesnap-certs
  db.openelis.org:
    container_name: oesnap-database
    ports: !reset []
    volumes: !override
      - $SNAP/db:/var/lib/postgresql/data
  oe.openelis.org:
    container_name: oesnap-webapp
    ports: !reset []
    depends_on: !override
      db.openelis.org: { condition: service_healthy }
      certs: { condition: service_completed_successfully }
    networks: !override
      openelis-network: { ipv4_address: 172.21.1.121 }
    environment:
      - ANALYZER_BRIDGE_URL=
    volumes:
      - $SNAP/logs/oeLogs:/var/lib/openelis-global/logs
      - $SNAP/logs/tomcatLogs:/usr/local/tomcat/logs
      - $SNAP/properties:/var/lib/openelis-global/properties
  fhir.openelis.org:
    container_name: oesnap-fhir
    ports: !reset []
  frontend.openelis.org:
    container_name: oesnap-frontend
  proxy:
    container_name: oesnap-proxy
    ports: !override
      - "$PORT:443"
    volumes: !override
      - certs-vol:/etc/nginx/certs/
      - keys-vol:/etc/nginx/keys/
      - $SNAP/nginx.conf:/etc/nginx/nginx.conf:ro
  openelis-analyzer-bridge:
    container_name: oesnap-bridge
    profiles: [never]
secrets:
  common.properties:
    file: $SNAP/properties/common.properties
networks:
  openelis-network:
    name: oesnap-network
    ipam:
      config: !override
        - subnet: 172.21.1.0/24
YAML
SC config -q || die "snapshot compose file is invalid"

# --- rebuild the database copy --------------------------------------------
log "stopping the old snapshot"
SC down --remove-orphans >/dev/null 2>&1 || true
rm -rf "$SNAP/db.new"; mkdir -p "$SNAP/db.new"; chown 999:999 "$SNAP/db.new"; chmod 700 "$SNAP/db.new"
log "copying the database from this server's own Postgres (no WAN traffic)"
docker run --rm --network host --user 999:999 -e PGPASSWORD="$HA_REPLICATION_PASSWORD" \
  -v "$SNAP/db.new":/out --entrypoint pg_basebackup "$(db_image)" \
  -d "host=127.0.0.1 port=5432 user=replicator application_name=snapshot" -D /out -X stream -c fast
# make it an independent, writable copy: no standby settings, no slots
rm -f "$SNAP/db.new/standby.signal" "$SNAP/db.new/recovery.signal"
sed -i '/^primary_conninfo/d; /^primary_slot_name/d' "$SNAP/db.new/postgresql.auto.conf"
# the snapshot stack runs on its own Docker network (172.21.1.0/24) and needs no replication access
python3 - "$SNAP/db.new/pg_hba.conf" <<'PY2'
import re, sys
p = sys.argv[1]; t = open(p).read()
t = re.sub(r"\n?# BEGIN openelis-ha.*?# END openelis-ha\n?", "\n", t, flags=re.S)
t = t.replace("172.20.1.0/24", "172.21.1.0/24")
open(p, "w").write(t)
PY2
rm -rf "$SNAP/db"; mv "$SNAP/db.new" "$SNAP/db"

log "starting the snapshot stack"
SC up -d
webapp_wait_healthy oesnap-webapp
reindex oesnap-webapp
date -u +%FT%TZ > "$SNAP/LAST_REFRESH"
log "snapshot ready on https://<this server>:$PORT/ (data as of $(cat "$SNAP/LAST_REFRESH"))"
